version: "2.4"

services:
  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper

  solr:
    image: solr:8.11.0-slim
    container_name: solr
    depends_on:
      - zookeeper
    environment:
      - ZK_HOST=zookeeper:2181
      - SOLR_OPTS=-Denable.packages=true
    ports:
      - 8983:8983
    volumes:
      - ./security.json:/opt/solr/server/solr/security.json
      - ./clusterprops.json:/opt/solr/server/solr/clusterprops.json

  repo:
    image: halverneus/static-file-server:latest
    environment:
      - "FOLDER=/www"
    volumes:
      - "../target:/www"
