version: "2.4"

services:
  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper

  solr:
    image: solr:8.11.0-slim
    container_name: solr
    depends_on:
      - zookeeper
    environment:
      - ZK_HOST=zookeeper:2181
    ports:
      - 8983:8983
    volumes:
      - ./security.json:/opt/solr/server/solr/security.json
      - ../target/solr-forward-authentication-plugin-0-SNAPSHOT.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/solr-forward-authentication-plugin.jar
