version:  "2.4"

services:
 zookeeper:
  image: zookeeper:3.6

 solr:
  image: solr:8.11.0-slim
  depends_on:
   - zookeeper
  environment:
   - ZK_HOST=zookeeper:2181
  volumes:
    - ./security.json:/opt/solr/server/solr/security.json
